const SET_ADDRESS = "SET_ADDRESS";
const SET_COORDINATE = "SET_COORDINATE";
const SET_TOGGLE_OPEN = "SET_TOGGLE_OPEN";
const SET_TOGGLE_CLOSE = "SET_TOGGLE_CLOSE";
const SET_FULL_ADDRESS = "SET_FULL_ADDRESS";

export {
  SET_ADDRESS,
  SET_COORDINATE,
  SET_TOGGLE_OPEN,
  SET_TOGGLE_CLOSE,
  SET_FULL_ADDRESS,
}